[root]
children = ["html"]

[html]
children = ["head", "body"]

[head]
children = ["meta", "title", "style"]

[meta]
charset = "UTF-8"

[title]
children = ["A Beautiful TOML Page"]

[style]
children = ["""
* {
  box-sizing: border-box;
}
html, body {
  margin: 0;
  padding: 0;
  height: 100%;
  font-family: 'Segoe UI', sans-serif;
  background: #fdfdfd;
  color: #333;
}
body {
  display: flex;
  justify-content: center;
  align-items: flex-start;
  padding: 2rem;
}
.container {
  width: 100%;
  max-width: 800px;
  padding: 1rem;
  line-height: 1.6;
}
header.site-header {
  text-align: center;
  margin-bottom: 2rem;
}
header.site-header h1 {
  font-size: 2.5rem;
  margin-bottom: 0.2rem;
}
.site-nav {
  font-size: 1rem;
  color: #555;
}
.inline-code {
  font-family: monospace;
  background: #f0f0f0;
  padding: 0.2em 0.4em;
  border-radius: 4px;
}
footer.footer {
  margin-top: 3rem;
  text-align: center;
  display: flex;
  justify-content: center;
  flex-direction: column;
  padding: 0.8rem;
  color: #888;
}
a {
  color: #555;
  text-decoration: none;
}
a:hover {
  text-decoration: underline;
}
"""]

[body]
children = ["container"]

[container]
children = ["header", "main", "footer"]
class = "container"

[header]
children = ["h1", "nav"]
class = "site-header"

[h1]
children = ["Welcome to Web4"]

[nav]
children = ["Home", " | ", "About", " | ", "Contact"]
class = "site-nav"

[main]
children = ["p1", "p2"]
class = "content"

[p1]
children = ["This is a clean and structured HTML page generated from TOML. "]

[p2]
children = ["Try editing ", "code", " yourself!"]

[code]
children = ["index.toml"]
class = "inline-code"

[footer]
children = ["p3", "p4"]
class = "footer"

[p3]
children = ["(c) 2025 smv. Powered by Web4."]

[p4]
children = ["View at ", "a#gh-link"]

["a#gh-link"]
children = ["s-mv/web4"]
href = "https://github.com/s-mv/web4"

